### ISSUE TITLE
Docker compose commands time out

### ISSUE THREAD

**Issue by noahsw** [dduportal/boot2docker-vagrant-box#21] opened 2015-05-18 16:08 UTC
I have everything working with normal docker:

```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from hello-world
a8219747be10: Pull complete
91c95931e552: Already exists
hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
Status: Downloaded newer image for hello-world:latest
Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (Assuming it was not already locally available.)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
```

```
$ docker info
Containers: 1
Images: 2
Storage Driver: aufs
 Root Dir: /mnt/sda2/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.2-boot2docker
Operating System: Boot2Docker 1.6.1 (TCL 5.4); master : 43209d4 - Thu May  7 22:06:28 UTC 2015
CPUs: 1
Total Memory: 1.465 GiB
Name: boot2docker
ID: MBPZ:LYOH:LV6D:T3PM:U5GS:6OU5:4RHF:AHO5:WCAC:TTAQ:QYMB:LBHZ
Debug mode (server): true
Debug mode (client): false
Fds: 10
Goroutines: 17
System Time: Mon May 18 16:03:20 UTC 2015
EventsListeners: 0
Init SHA1: 2dabfc43e5f856a0712787a6ff78ceaf791cc9e7
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda2/var/lib/docker
Username: hidden
Registry: [https://index.docker.io/v1/]
```

But when I run my `docker-compose` command, I get a timeout:
```
$ docker-compose ps
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 191, in ps
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 229, in containers
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 385, in containers
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 82, in _get
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 395, in get
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 387, in send
requests.exceptions.Timeout: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103b9ffd0>, 'Connection to 192.168.59.103 timed out. (connect timeout=60)')
```

Everything worked fine with boot2docker. I haven't touched the default Vagrant file and this is my `boot2local.sh`:

```
#!/bin/sh

# Regenerate certs for the newly created Iprivate network IP
sudo /etc/init.d/docker restart
# Copy tls certs to the vagrant share to allow host to use it
sudo cp -r /var/lib/boot2docker/tls /vagrant/
```

I also have:
```
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/me/Projects/project-name/src/tls
export DOCKER_TLS_VERIFY=1
export B2D_NFS_SYNC=1
```

**Comment by dduportal** [comment] 2015-05-28 06:15
Hi @noahsw !

Thank you for your feedback.

It's odd, i bet it's around SSL encryption. My first thought is that it can be related with some Virtualbox behavior, around date?time inside the VM, that can change the SSL handshakes and timestamping.


Which version of Virtualbox are you running ?

**Comment by noahsw** [comment] 2015-05-31 03:23
4.3.26

**Comment by dduportal** [comment] 2015-05-31 09:47
Thanks !

I think that the virtual box version you are running is older than the version of the "vbox add ons" built inside boot2docker, which cause some weird behavior around clock syncing between host and VM.
=> direct impact is bad ssl handshake, who need time sync.

Could you please try :
* Updating to latest virtual box (4.3.28 when writing those lines)
* Get the latest version of the box, the [1.6.2](https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.6.2) 
* Try to reproduce your behavior with a brand new instance of the VM (vagrant destroy if you want to re-use your existing Vagrantfile, to ensure we don't use anymore the old box version)

Sorry for the inconvenience

**Comment by noahsw** [comment] 2015-05-31 17:16
VirtualBox is saying no updates are available. I don't see 4.3.28 on http://www.oracle.com/technetwork/server-storage/virtualbox/overview/index.html

Anyways, I basically started from scratch and upgraded to boot2docker 1.6.2. 

Now I have a different problem. My nginx container won't start:
```
╰─± docker-compose up
Recreating src_dbdata_1...
Recreating src_db_1...
Recreating src_webapp_1...
Cannot start container 0f37ba6b4e72ecdb682ee570d5d49c25e6b02e11a0d61b062a12f9ec05e7e3e1: [8] System error: no such file or directory
```

Here is my `docker-compose.yml` file:
```
nginx:
  extends:
    file: docker-common.yml
    service: nginx
  links:
    - webapp

webapp:
  extends:
    file: docker-common.yml
    service: webapp
  links:
    - db
  volumes:
    - webapp:/webapp

db:
  extends:
    file: docker-common.yml
    service: db
  volumes_from:
    - dbdata

dbdata:
  extends:
    file: docker-common.yml
    service: dbdata
```

I saw in #20 that there are issues with mounting folders. Could that be the culprit? I'd really like to avoid modifying my `docker-compose.yml` file as other devs may be using vanilla boot2docker.

**Comment by dduportal** [comment] 2015-05-31 20:56
Hello @noahsw , it seems that virtual box and Oracle server are in trouble those days :(

The official website was http://virtualbox.org but it seems down. Use the Download server instead : http://dlc-cdn.sun.com/virtualbox/4.3.28/index.html 

Concerning your new problem, i miss some critical information : what is the content of your docker-common.yml, which is extended by the docker-compose.yml file you provided ?
Your problem does not seems to be related to the basebox, but I need to understand what you're doing to help you.

**Comment by noahsw** [comment] 2015-06-01 02:43
You can see my `docker-compose.yml` and `docker-common.yml` at https://github.com/league-wins-pool/league-wins-pool/tree/develop/src.

It's really weird that this container won't start. I've been playing around with a few "docker on OSX" solutions and they all run `docker compose` just fine.

**Comment by dduportal** [comment] 2015-06-26 14:12
Hello @noahsw !

As an update, could you please try to reproduce using :
* Latest version of the box (1.7.0), just released : https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.7.0
* Using latest version of docker-compose (1.3.1) ?

**Comment by dduportal** [comment] 2015-08-11 07:04
Closing the issue (requester timeout :) ) Feel free to reopen with latest tests on the latest box (1.7.1)

**Closed by dduportal** 2015-08-11 07:04 UTC
